---
### Base load balancer - we do not need ENTRYPOINT - provides an access to the Ingress
#  apiVersion: v1
#  kind: Service
#  metadata:
#    name: buggyapp-entrypoint
#  spec:
#    type: LoadBalancer            # for access to ingress
#    ports:
#    - port: 80
#      protocol: TCP    
#      targetPort: 80 # Ingress is still on 80
#    selector:
#      #name: buggyapp-traefik-ingress
#      name: buggyapp-traefik-ingress
---
## Ingress load balancer
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: buggyapp-traefik-ingress
    labels:
      name: buggyapp-traefik-ingress
    annotations:
      kubernetes.io/ingress.class: traefik
  spec:
    backend: #it works
      serviceName: buggyapp
      servicePort: 8080
    #rules: #it works too
    #- http:
    #    paths:
    #    - path: /
    #      backend:
    #        serviceName: buggyapp
    #        servicePort: 8080
---
## Service
  apiVersion: v1
  kind: Service
  metadata:
    name: buggyapp
  spec:
    ports:
    - port: 8080
      protocol: TCP    
      targetPort: 8080
    selector:
      app: buggyapp
---
## Deployment
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: buggyapp
  spec:
    selector:
      matchLabels: 
        app: buggyapp
    replicas: 3
    minReadySeconds: 15
    strategy:
      type: RollingUpdate
      rollingUpdate: 
        maxUnavailable: 1
        maxSurge: 1
    template:
      metadata:
        labels:
          app: buggyapp
      spec:
        containers:
          - image: sergeimelman/buggyapp:1
            imagePullPolicy: Always
            name: buggyapp
            ports:
              - containerPort: 8080
            livenessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 3
              periodSeconds: 3
              timeoutSeconds: 1
              successThreshold: 1
              failureThreshold: 1
            resources:
              limits:
                memory: "1G"
                #cpu: "500m" # equal to 0.5 cpu
              requests:
                memory: "10M"
                #cpu: "400m"
            #readinessProbe:
            #  httpGet: {path: /health1, port: 8080}
            #  initialDelaySeconds: 5
            #  periodSeconds: 5
---
