apiVersion: extensions/v1beta1
kind: Deployment                                          # 1
metadata:
  name: buggyapp
spec:
  selector:
    matchLabels: 
      app: buggyapp
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: buggyapp                                     # 6
    spec:
      containers:
        - image: sergeimelman/buggyapp:7
          imagePullPolicy: Always                         # 7
          name: buggyapp
          ports:
            - containerPort: 8080
          #livenessProbe:
          #  httpGet:
          #    path: /health1
          #    port: 8080
          #  initialDelaySeconds: 3
          #  periodSeconds: 3
          #readinessProbe:
          #  httpGet: {path: /health1, port: 8080}
          #  initialDelaySeconds: 5
          #  periodSeconds: 5
          #resources:
          #  memory: 1Gb             